roots/sage

assets/styles/main.scss.example, bower.json, package.json
* Introduce `main.scss.example`
* Add `bootstrap-sass-official` asset overrides to `bower.json`
* * *
How to get started using Bootstrap Sass:
1. Run `bower install bootstrap-sass-official --save`
2. Rename `main.scss.example` file to `main.scss` and remove `main.less`
3. Update the `assets/manifest.json` styles dependencies to change `main.less` to `main.scss`
=> Add example of how to use bootstrap-sass

README.md
ref https://github.com/roots/roots/issues/1252
=> Add bower install to readme

README.md, assets/manifest.json, bower.json, gulpfile.js, package.json
Simplifies and consolidates gulp tasks
Adds a --production flag to disable source maps
=> Use new manifest format

gulpfile.js
Adding live reload triggers to JS and CSS changes.
=> Adding live reload triggers to JS and CSS changes.

assets/scripts/main.js
Addresses https://github.com/roots/roots/commit/d6fc59e0417dccc62bf2644395aa33f946024f78#commitcomment-6183775
=> Adding JavaScript finalize back in

CHANGELOG.md, README.md, lib/assets.php, templates/entry-meta.php, templates/head.php, templates/header.php, templates/page-header.php, templates/searchform.php
See http://php.net/manual/en/function.echo.php
=> [8.0.0] Use short echo syntax, bump required PHP version to 5.4

CHANGELOG.md, functions.php, lib/assets.php, lib/config.php, lib/gallery.php, lib/init.php, lib/nav.php, lib/sidebar.php, lib/wrapper.php, templates/comments.php, templates/content-page.php, templates/content-single.php, templates/header.php
See http://php.net/manual/en/language.types.array.php
=> [8.0.0] Use short array syntax

.travis.yml
Edits according to the travis-ci.com docs: http://docs.travis-ci.com/user/languages/php/#Choosing-PHP-versions-to-test-against
=> Formatting edits for `travis.yml`

.jshintrc
fixes https://github.com/roots/roots/issues/1275
ref https://github.com/jshint/jshint/pull/1554
=> remove trailing option

.travis.yml, CHANGELOG.md, base.php, lib/assets.php, lib/config.php, lib/nav.php, lib/sidebar.php, lib/wrapper.php, ruleset.xml, templates/comments.php, templates/header.php
* Add Roots coding standards based on PSR-2
* Add PHPCS to Travis
* Update PHP files to pass coding standards
Closes #1176
=> [8.0.0] Coding standards, run PHP_CodeSniffer on Travis

.jscsrc, .travis.yml, assets/scripts/main.js, gulpfile.js, package.json
install JSCS globally npm install jscs -g
use `npm run jscs`
Now as far as actually fixing the issues.....
uses google styleguide: https://github.com/jscs-dev/node-jscs/blob/master/presets/google.json
=> Adds JSCS for gulpfile and scripts

gulpfile.js
was causing the rev manifest to bomb out
=> Fixes revved files base

assets/manifest.json, gulpfile.js, lib/assets.php, package.json
Like said in https://github.com/roots/roots/issues/128, here's a first try with browserSync.
In gulpfile.js people might need to change the proxy from *localhost* if they are using another local host name.
I tested with *.php changes and it works, but I couldn't test with styles and scripts (I'm getting independent errors).
=> browserSync

gulpfile.js
Found some random spelling and general errors in the notes for the gulpfile. My OCD wouldn't let it fly. PR requested by @austinpray.
=> fix a few errors in notes of gulpfile

ruleset.xml
=> Fix typo in PHPCS ruleset comment

gulpfile.js
Cleans up capitalization and punctuation.
Cleans up example code formatting
=> Documents BrowserSync in gulpfile.

package.json
use carrot to get latest minor version as well
ref https://github.com/austinpray/asset-builder/issues/14
=> Bumps asset-builder verison

bower.json
Override directories weren't correct on a few of the bootstrap-sass assets.
=> Fixing bootstrap-sass overrides

.travis.yml, README.md, package.json
The npm that ships with 0.10 is 1.2.x and it is riddled with
race conditions.
=> Require the latest version of npm

gulpfile.js, package.json
* Bump BrowserSync version
* Update whitelist/blacklist
Ref #1298
=> BrowserSync tweaks

index.php, single.php
See #1033 
If your CPT is named `movie`:
* archive pages will attempt to load `templates/content-movie.php`
* single posts will attempt to load `templates/content-single-movie.php`
=> Ref #1033 - better support for CPT templates

404.php
Related: https://github.com/h5bp/html5-boilerplate/commit/782aefab7ea7ae57d30b237be5823298c053136d
=> Simplify 404 page

bower.json
this file is not copied to dist/ currently
=> add bootstrap glyphicons woff2 to bower.json

package.json
https://github.com/plus3network/gulp-less/commit/3fae01b690ca910a8902a6702bbc9dfdf9d39d17
=> Bumping gulp-less to 3.0.1

gulpfile.js
fixes https://github.com/roots/roots/issues/1340
=> Only save a wiredepped file if Sha1 differs

templates/header.php
A small change to keep strings in templates consistent. Output is the same as before as no translation exists yet.
=> added localized string for 'Toggle navigation' in /templates/header.php

lib/assets.php, lib/config.php
=> Use a constant for the build directory path

package.json
=> Bump gulp-plumber to 1.0.0

package.json
=> Temporary sourcemaps fix

lib/config.php, lib/nav.php, templates/header.php
Same as previous PR, simply referencing classes directly and avoiding using the last namespace when new upping.
=> Referencing ConditionalTagCheck directly

lib/nav.php
minor edit
for consistency with #1390
=> Change SageNavWalker to NavWalker in comments

README.md
oops, not sure how we (I) missed that. :mag:
=> use the right words

assets/styles/main.scss.example
=> Clarify Sass integration

CHANGELOG.md, README.md, lib/config.php
~~Implements https://github.com/roots/soil/pull/58~~ 
this PR has been updated to remove the mention of GA from `lib/config.php`
=> Remove mention of Google Analytics from the config

CHANGELOG.md, templates/head.php
See https://github.com/h5bp/html5-boilerplate/issues/1656
=> From H5BP: Lowercase X-UA-Compatible

gulpfile.js
ref https://discourse.roots.io/t/compiled-assets-have-incorrect-file-path/3672/8
closes https://github.com/roots/sage/issues/1449
=> Fix incorrect file path in compiled assets

CHANGELOG.md, search.php, templates/content-search.php
=> Add search templates

README.md
Ref https://github.com/roots/sage/commit/ca0f1c2a63f678889122730bc96618e5c9824b6e and https://github.com/roots/soil/commit/9fe32088d9933ebe63710e68f311d48b3ccf5c06
Just moving the line down.
=> Nav cleanup is in Soil now, updating documentation.

base.php, templates/head.php
Still using the `head.php` partial at this point.
=> Moved opening html tag to base.php

assets/manifest.json, bower.json
=> Remove unnecessary references to jQuery

bower.json
=> Update bootstrap-sass-official to 3.3.5

assets/manifest.json
Cause that happened, not blaming anyone
=> Fix jQuery being compiled in main.js

base.php, templates/footer.php, templates/header.php
Removed redundant ARIA roles
Added `nav-primary` class to main navigation
=> Removing redundancy with WAI-ARIA in HTML

lib/setup.php
Sorry I forgot this. Per @aumo's request: https://github.com/JulienMelissas/sage/commit/5a621210db943b90aa7c6a92a7908882b96c1beb#commitcomment-13791685
=> Added note about tinymce file

style.css
Text Domain must be declared, if we want to translate custom page templates names.
=> Declare Text Domain in style.css

CHANGELOG.md, bower.json
see http://blog.getbootstrap.com/2015/11/24/bootstrap-3-3-6-released/
=> Update to Bootstrap 3.3.6

CHANGELOG.md, README.md, composer.json
Still gotta add it to Packagist for this to work.
=> Add composer.json and update installation instructions

CHANGELOG.md, package.json, style.css
only change from 8.4.0 is adding a `composer.json` file (#1583)
=> Sage 8.4.1

src/filters.php
https://github.com/roots/sage/issues/1624
=> is_page_template() requires the name of the subfolder

package.json
Bootstrap 4.0.0-alpha.2 on NPM
https://github.com/twbs/bootstrap/issues/18006
=> Bootstrap NPM ^4.0.0-alpha.2

package.json
See https://github.com/roots/sage/issues/1648
=> Update gulp-if, fix #1648

package.json
=> Fix package.json whitespace

.github/ISSUE_TEMPLATE.md
https://github.com/roots/trellis/pull/594#issuecomment-225573519 - looks like I missed this one
=> Add contributing guidelines to GitHub issue template

CHANGELOG.md, src/setup.php
=> Remove post formats

CHANGELOG.md, src/filters.php, src/helpers.php
don't show the sidebar on any pages by default
todo:
=> Remove sidebar defaults

assets/build/webpack.config.js
=> Fix to load optimization config (#1761)

src/filters.php
Correct the value based on what WordPress passes as filter values
https://github.com/WordPress/WordPress/blob/4.7-branch/wp-includes/template.php#L29-L41
=> front_page => frontpage

src/admin.php, src/setup.php
see https://make.wordpress.org/core/2016/03/22/implementing-selective-refresh-support-for-widgets/
also ~~added~~ updated selective refresh support for the blog name
=> Enable selective refresh for widgets in customizer

.travis.yml, README.md, package.json
=> Update clean task name

CHANGELOG.md, composer.json, src/lib/Sage/PostCreateProject.php
font awesome was removed by default with #1809
this adds an option via composer post install cmds to bring it back
=> Add option to add Font Awesome

composer.json
Fixes #1842
See composer note at https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
💌
=> Fix call to composer package binaries

composer.json, composer.lock
This PR provides the upgrade suggested in #1841
=> Upgrade to Illuminate 5.4 packages #1841

README.md
Referencing: https://discourse.roots.io/t/undefined-function-app-get-theme-file-path/8455
=> Add requirement note for Wordpress 4.7

app/filters.php
Fix regression, see https://github.com/roots/sage/commit/6ca3b3faa7e3ec29d01016fdc7bd656ff0e8a64e
=> front_page -> frontpage

resources/views/index.blade.php
=> Remove post format reference in template call

app/lib/Sage/PostCreateProject.php
=> Don't remove comments when clearing files.

resources/views/single.blade.php
Addresses [comment](https://github.com/roots/sage/pull/1904#commitcomment-22524338) by dirad to make template call syntax uniform amongst files.
=> Change syntax of template call to match other files in views/

CHANGELOG.md, composer.json, composer.lock, package-lock.json, package.json, resources/assets/build/webpack.config.js, resources/assets/styles/common/_variables.scss, resources/style.css, yarn.lock
https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/
=> Bootstrap 4 Beta, Sage 9.0.0-beta.4

CHANGELOG.md, bower.json
=> Sage 8.5.3

README.md
=> Update version number in composer install command.

composer.json, composer.lock
Update composer.json to use Controller 9.0.0-beta.4
=> Controller 9.0.0-beta.4

README.md
The composer command incorrectly references 8.5.2 for release tagged 8.5.3
=> README.md incorrectly references 8.5.2

CHANGELOG.md, package-lock.json, package.json, yarn.lock
http://blog.getbootstrap.com/2017/10/19/bootstrap-4-beta-2/
=> Update to Bootstrap 4 Beta 2

resources/assets/build/webpack.config.optimize.js
Fixes issue #2043 
Adjusts the structure of the configuration object passed to SVGO to match the expected format, as shown in the [imagemin-svgo documentation](https://github.com/imagemin/imagemin-svgo/blob/07aad157c0223e817b510432274c74b1a32ef07b/readme.md) and [svgo examples](https://github.com/svg/svgo/blob/3ec6cef333ef9106eab7f880dab9a76997101724/examples/test.js)
=> Fix default SVG optimisation configuration

CHANGELOG.md, composer.json, composer.lock, resources/functions.php
x-ref https://github.com/roots/sage-lib/commit/36573cd93b8109633c953e3f05b9f7d654bad885
x-ref https://github.com/roots/sage-installer/commit/56f833530f67a9483d5d50d2311f2b998e1a8a45
close #1962
=> Bump to Laravel 5.6

app/filters.php
- Right now comments template is rendered without data from the controller. This pull request fixes that.
- Filter that renders template should have PHP_INT_MAX priority.
=> Add data from controller to comments template

resources/assets/build/webpack.config.js
See #2119.
@LubomirGeorgiev Thank you for bringing this up!
=> Add note regarding webpack.config.preset.js usage

.travis.yml, CHANGELOG.md, README.md, composer.lock, package-lock.json, package.json, yarn.lock
https://blog.getbootstrap.com/2018/12/21/bootstrap-4-2-1/
=> Sage 9.0.6: Update to Bootstrap 4.2.1

CHANGELOG.md, composer.json, composer.lock, package-lock.json, package.json, resources/style.css, yarn.lock
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
=> Update to Bootstrap 4.3.1 (9.0.9)

.circleci/config.yml
Let's aim for less than 30 seconds.
See: https://circleci.com/gh/TangRufus/workflows/sage/tree/circleci
=> Optimize CircleCI config

README.md, resources/functions.php
Minimum WordPress version needs bumped with the addition of #2167
=> Bump required WordPress version

composer.json
Related: https://github.com/roots/acorn/pull/20
=> Add post-autoload-dump script for package discovery

app/Composers/Alert.php, app/Providers/ThemeServiceProvider.php, config/view.php, resources/views/404.blade.php, resources/views/components/alert.blade.php, resources/views/index.blade.php, resources/views/partials/comments.blade.php, resources/views/search.blade.php
=> Create + alias alert component with view composer

app/Providers/ThemeServiceProvider.php, composer.lock, config/view.php
=> Move alert Blade component alias to view config

app/Composers/Alert.php, composer.lock
Merge with [Acorn#36](https://github.com/roots/acorn/pull/36)
=> Use $this->data in the Alert Composer

index.php
This fixes error reporting for Blade views.
=> Call ->render() on view instead of relying on toString

CHANGELOG.md
I found two typos in the latest changes.
=> Fix typos in latest changes

composer.json, composer.lock
This PR updates the `composer/installers` package so the sage theme is compatible with Composer 2.
Fixes https://github.com/roots/sage/issues/2568.
=> Update composer/installers for compatibility with Composer 2

tailwind.config.js
=> Shorter syntax for purge files

composer.lock, package.json, yarn.lock
- chore(deps): Bump dependencies
=> Bump dependencies

resources/scripts/app.js
[jQuery 3 recommends `$(handler)` syntax.](https://api.jquery.com/ready/)
=> Remove deprecated jQuery .ready() syntax

package.json
=> Enable Webpack 5's automatic unique naming

bud.config.js
Fixes https://github.com/roots/sage/issues/2863
=> Fix assets path for static images

README.md
there's some confusion about which version of sage 10 some folks are grabbing.
* `10.0.0-beta.1`: sage 10 with mix
* `master` (as of right now): sage 10 with bud (in development, looking for more users and bug reports 💜 )
=> README: Mention Sage 10 beta releases

package.json, yarn.lock
https://tailwindcss.com/blog/tailwindcss-v3
=> Update to Tailwind CSS v3.0

bud.config.js
ref https://github.com/roots/bud/pull/776
=> Fix Bud proxy

bud.config.js
glob now tracks all `*.blade.php` files in `resources/views` directory.
=> improve: watched files glob

package.json, yarn.lock
🎄🎄🎄 all i want for xmas is grouped dependabot PR's 🎄🎄🎄
closes #2903
closes #2902
=> chore(deps-dev): Bump @roots/bud to v5.0.0-next.20

package.json, yarn.lock
https://github.com/roots/bud/releases/tag/v5.0.0
=> chore(deps-dev): Bump @roots/bud to v5.0.0

resources/views/components/alert.blade.php, resources/views/forms/search.blade.php, resources/views/layouts/app.blade.php
=> Remove all base styles followup

CHANGELOG.md, style.css
https://github.com/roots/sage/milestone/7
=> Sage 10.0.0-beta.2

composer.json
ref https://github.com/roots/acorn/releases/tag/v2.0.0-beta.7
=> chore(deps): Bump roots/acorn to v2.0.0-beta.7

.eslintrc.js, package.json, yarn.lock
=> Bump eslint to 8.6.0

.github/workflows/main.yml, README.md, composer.json, style.css
PHP 7.3 is past EOL so we will no longer be supporting it.
=> Bump minimum PHP version to 7.4

resources/views/partials/content-search.blade.php, resources/views/partials/content-single.blade.php, resources/views/partials/content.blade.php
I have no idea how this went unnoticed for so long lol
=> fix(views): Use dot notation on entry-meta view includes

resources/scripts/editor.js
=> fix(bundle-editor): remove `@wordpress/edit-post`

composer.json
https://github.com/roots/acorn/releases/tag/v2.0.0-beta.8
=> chore(deps): Bump roots/acorn to v2.0.0-beta.8

package.json
=> Re-add i18n related scripts/tasks

README.md, app/setup.php, style.css, theme.json
ref https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/
=> 🔧 migrate global settings to `theme.json`

README.md, composer.json, functions.php
=> Remove Acorn as dependency; treat as requirement

composer.json
=> 🔧 remove acorn post-autoload-dump

functions.php
=> 💬 acorn requirement error: add link to install docs

package.json, yarn.lock
https://bud.js.org/blog/5.5.0/
props @kellymears @strarsis @joshuafredrickson
=> ⬆️ bud v5.5.0

.eslintrc.js, .github/workflows/main.yml, .prettierrc, .stylelintrc, package.json, yarn.lock
=> 🔥 remove linting

tailwind.config.js
https://tailwindcss.com/docs/upgrade-guide#remove-variant-configuration
=> chore(deps): Remove deprecated variant configuration from tailwind config

.github/workflows/discourse.yml
=> ✨ add discourse topic release workflow

package.json, yarn.lock
https://bud.js.org/blog/5.6.0
> bud is now about 30% faster 🎉.
=> ⬆️ bud v5.6.2

package.json, yarn.lock
https://github.com/roots/bud/releases/tag/v5.7.4
=> ⬆️ bud 5.7.4

bud.config.js, package.json, yarn.lock
=> ⬆️ bud 5.7.6

package.json, yarn.lock
https://github.com/roots/bud/releases/tag/v5.7.7
=> ⬆️ bud 5.7.7

app/setup.php
=> 🎨 Add trailing commas

.github/workflows/formatting.yml, .github/workflows/main.yml
Closes #3078 
Ref https://github.com/aglipanci/laravel-pint-action
=> 👷 CI: Run Pint

resources/views/partials/content-single.blade.php, resources/views/partials/entry-meta.blade.php
Ref https://microformats.org/wiki/h-entry
=> 🔍️ Posts: Use latest h-entry microformat

resources/scripts/editor.js, resources/scripts/filters/button.filter.js
See https://github.com/roots/sage/issues/3030#issuecomment-1488412148
Closes https://github.com/roots/sage/issues/3030
=> 🩹 fix: core/button block style

bud.config.js, jsconfig.json, package.json, theme.json, yarn.lock
- Upgrade [@roots/bud](https://github.com/roots/bud) to 6.16.1.
- Improve: use `bud.wpjson.setSettings` for better type hinting.
=> 📦 deps: upgrade @roots/bud to 6.16.0

app/setup.php
Soil is being retired in favor of a new Acorn package, see https://github.com/roots/acorn-prettify and https://roots.io/announcing-acorn-prettify/
=> 🔥 Remove Soil features

.github/workflows/main.yml, composer.json
ℹ️ Acorn v4 will be released soon and requires PHP 8.1
=> 🔧 Bump minimum PHP version to 8.1

app/View/Composers/Comments.php, resources/views/partials/comments.blade.php
=> 🎨 Move comment logic into a dedicated Composer

resources/views/layouts/app.blade.php
=> Add missing text domain to skip link

resources/js/app.js
Similar to .assets(["images"]) in bud, we can add static assets in vite.
See [https://laravel.com/docs/11.x/vite#blade-processing-static-assets](https://laravel.com/docs/11.x/vite#blade-processing-static-assets)
=> Import static assets

vite.config.js
Ref https://vite.dev/guide/build.html#public-base-path
=> 🔧 Set public base path

resources/js/build/wordpress.js, vite.config.js
=> 🩹 Dev server: fix WP dependency handling
