gulpfile.js
package.json

wiredep now only touches your files if the destination file is different
from the source file
There were a couple issues such as the wiredep task not returning a stream and a couple race conditions.

Fixes watch and wiredep

---

lib/assets.php

The current logic for condtionally including the GA snippet is confusing (see #1232, #1188 and [here](http://discourse.roots.io/t/google-analytics-condition-seems-off/2778/4)) and bit inconsistent. In development you would see logging when the snippet wasn't included but this wouldn't happen if you were a logged in admin.
Now there's only two cases:
1. Production non admin user: GA snippet is loaded.
2. Anything else (development or admin user): log output

Improve Google Analytics conditional loading

---

gulpfile.js
package.json

Speaking with @austinpray, lodash is not needed anymore.

remove lodash from gulpfile and package.json

---

gulpfile.js

Whitelists js and css and does not send maps to browsersync.
ref: https://github.com/roots/roots/issues/1287#issuecomment-72085636
ref: http://discourse.roots.io/t/gulpfile-with-browsersync/2834/2

Fixes browsersync hard refresh

---

templates/content-page.php

wp_link_pages is now included in posts and pages with the same structure. Removed Bootstrap class.

Uniform wp_link_pages between posts and pages

---

.travis.yml

`cache: npm` isn't even a valid config anyway
https://stackoverflow.com/questions/15393821/npm-err-cb-never-called/15483897#15483897
https://github.com/sass/node-sass/issues/638

Fix node-sass and npm cache on travis

---

gulpfile.js

Code from https://github.com/roots/roots/issues/1298#issuecomment-72369925
Closes https://github.com/roots/roots/issues/1298

Added wp-admin pages to browserSync ignore path.

---

lib/assets.php

Memoize asset_path function
Previously roots would do a file operation each time asset_path is
called. So if you enqueued modernizr, jquery, and main.js it would read and parse dist/assets.json three times. Now it will only parse the json manifest one time per program execution.
Extract json reading to class that can be used to read bower.json
fix https://github.com/roots/roots/issues/1286

[8.0.0] reconcile bower dependency versions with CDN url

---

assets/manifest.json

See https://discourse.roots.io/t/adding-none-bower-js-libs-to-gulp-manifest-json/2890?u=austin

Remove /**/* glob from js by default

---

lib/init.php

This fixes the admin side editor to use theme styles.

use correct editor-style.css filename for tinymce editor

---

gulpfile.js

because otherwise you'll occassionally run into broken SVG images

Disable removeUnknownsAndDefaults on svgo

---

lang/sage.pot

`msgid` and `msgstr` should always be in pairs.
http://www.gnu.org/software/gettext/manual/gettext.html#PO-Files

Fix missing "msgstr" in .POT

---

lib/nav.php
lib/utils.php

what @Foxaii's nav-rejig does:
* fixes the default WordPress functionality where your blog/posts page is shown as **active** when viewing a single CPT post
* marks the proper menu item as active when necessary for CPT archives and CPTs
needs a code review and possible cleanup before merge

Migrate @Foxaii's nav-rejig for 8.0.0

---

gulpfile.js

If the `--production` flag is set: hard fail the build if there is a
precompiler error. If unset, log an error and end the task
successfully.
fixes https://github.com/roots/roots/issues/1288

fix less breaking during watch on error

---

CHANGELOG.md
package.json

Bumps asset-builder to 1.0.1
Closes https://github.com/roots/sage/issues/1351

Adds windows compatibilty

---

lib/gallery.php

Issue is if you set 3 in Gallery options it will output 4 columns in the frontend. The default WordPress column is 3 for gallery and if it's set to 3, it does not added any column attribute to the shortcode which cause the issue. Setting the default to 3 should fix the issue.

change default columns to 3.

---

lib/assets.php

Based on this thread: https://discourse.roots.io/t/sage-and-augmenting-my-workflow/2965/3
This sets up the opportunity to change the path of `dist/` for those needing to reference a different build.

Handle $dist_path as var

---

lib/conditional-tag-check.php
lib/config.php

When passing an argument to a function for ConditionalTagCheck, the argument should *not* always be an array. The function will be called wit the arguments as is and not modified. So if the function takes a string argument, keep it as a string. If it takes an array, use an array.

Update ConditionalTagCheck and usage docs

---

lib/assets.php

This makes the fallback URL play nicely with Soil's relative URLs module.

Apply script_loader_src filter to jquery fallback

---

gulpfile.js

Been using Sage on a project. I've found it slightly frustrating that adding something via Bower seems to be added, but since only `wiredep` is run, nothing actually compiles.
It might take a few extra seconds, but changing the task from `wiredep` to `build` when `bower.json` is changed should re-compile everything and have your shiny new Bower package compiled correctly

Run `build` if `bower.json` is changed

---

README.md
assets/manifest.json

Hopefully we get less of these threads: https://discourse.roots.io/t/browser-sync-wordpress-and-mamp/3061/7

Added more explicit instructions for BrowserSync.

---

lib/assets.php
lib/config.php

Be sure to merge this PR first: https://github.com/roots/soil/pull/56

Move GA snippet to roots/soil

---

gulpfile.js

Working on a project, when I want to modify manifest.json it helps the workflow if I don't need to run `gulp` every time I make a change.

Watch manifest.json

---

CHANGELOG.md
gulpfile.js
package.json

Prevents potential race condition where styles and scripts write to the
manifest at the same time
fixes https://github.com/roots/sage/issues/1398
Updates changelog

Run styles and scripts in sequence

---

CHANGELOG.md
gulpfile.js
package.json

This gulp plugin was more trouble than it was worth.
ref https://github.com/roots/sage/issues/1386
ref https://discourse.roots.io/t/sourcemaps-no-longer-working-as-expected-with-sage-update/3022/1

Removes gulp-pleeease dependency

---

CHANGELOG.md
gulpfile.js
package.json

For our simple usecase we do not need the extra functionality of yargs.
This removes 4 dependencies from our dependency graph.
https://github.com/bcoe/yargs
https://github.com/substack/minimist

Switch from yargs to minimist

---

CHANGELOG.md
README.md
lib/assets.php
lib/config.php

See https://github.com/roots/soil/pull/64
Closes #1408

Move jQuery CDN feature to Soil

---

CHANGELOG.md
templates/head.php

moving forward, use `add_theme_support('automatic-feed-links');` in a site functionality plugin to add feed links
`add_theme_support('automatic-feed-links');` wasn't ever used in the starter theme since it adds additional (unnecessary, imo) feed links, such as for comments. related: https://github.com/roots/soil/issues/68

Remove hardcoded feed link

---

gulpfile.js

`gulp watch` was taking anywhere from 3 - 14 **minutes** (depending on disk activity, I assume) to start for me. This brings it down to a much more sane ~150ms.
The problem seems to be that `gulp watch` was walking all directories looking for PHP files, node_modules in particular. This limits it to `./`, `./lib/`, and `./templates/` directories.

Limit file patterns in gulp watch

---

gulpfile.js
package.json

Simplify the gulpfile by removing gulp-load-plugins dependency. Some
whitespace cleanup and formatting to match normal NPM conventions.

Remove gulp-load-plugins dependency

---

lib/assets.php

This change allows you to run `gulp --production` on your development environment and have the page load properly. `gulp --production` on dev breaks neat features of `gulp watch` like browsersync and so forth. However it does permit you to test the `--production` output locally before deployment.

Allow revved production files on dev environment

---

CHANGELOG.md
package.json

Bump node dependencies

---

assets/scripts/main.js

Now that the CDN option is in soil, there's no need for this information to be in the file (and it was outdated).

Remove jQuery CDN info

---

base.php

Since `get_footer()` is not used, `get_footer` template hooks needs to be triggered just like `get_header` does.

Trigger `get_footer` action before including footer template

---

gulpfile.js

Includes a cleanupIDs set to false option within the gulp images task in order to preserve the ID's set for internal SVG elements.

Keep SVG element IDs during gulp images task

---

lib/conditional-tag-check.php

The check returns false, if any of it's tags are true, not vise versa.
To be perfectly honest this behaviour seems opposite of what I'd expect (should return true if any of them are true) but it would be a breaking change, so for now just update the comments to match.

Adjust comments on ConditionalTagCheck to match actual functionality.

---

CHANGELOG.md
gulpfile.js

fixes https://github.com/roots/sage/issues/1480
cc @aaemnnosttv

Allow `debugger` statements in development JS

---

gulpfile.js

This sets the gulp-sourcemaps `sourceRoot` option, now pointing to the right locations of the source maps. Since it was not set, it was pointing to the default [`/source/`](https://github.com/floridoo/gulp-sourcemaps/blob/master/index.js#L191) folder, which is not the right folder.

Fix source map paths

---

.jscsrc

Replaced depricated validateJSDoc rule with jsDoc rule: http://jscs.info/rule/jsDoc.html

Update jscs validateJSDoc to jsDoc rule

---

templates/entry-meta.php

get_the_time('c') returns the local time in ISO 8601 format, but does
not fetch the related GMT timezone offset. This actually renders the incorrect time, as the timezone offset is always +00:00.
Google News, in particular, uses this time to show when an article was published. In our case it was always 7 hours too early because we are in GMT -7
get_post_time('c', true) is the correct function here, using the true parameter for GMT.

fix timezone offset in ISO 8601 date in byline

---

lib/wrapper.php

I experienced a conflict between Sage and a WPML and WooCommerce combination, where a translated product archive (specificly product_cat taxonomy page) wouldn't be wrapped in the base template. Just the template file contents would be executed without the master/base template. This could be solved by changeing the priority of the template_include filter for the wrapper to >100. I'm not sure if this is WooCommerce specific or if this would be the case for any translated taxonomy when using WPML.

Add compatibility with WooCommerce Multilingual plugin

---

lib/init.php

gallery was removed in #1421, but this simple addition enables the html5 gallery markup from wp core
(uses `<figure>` instead of a definition list)

Use WP core's HTML5 gallery markup

---

README.md
lib/config.php

WP_ENV is no longer required. previous dependencies on WP_ENV were removed in #1456 and #1382.

Remove references to WP_ENV

---

CHANGELOG.md
README.md
base.php
functions.php
lib/extras.php
lib/setup.php

Rename config.php to setup.php

---

lib/assets.php
lib/setup.php

Related: #1555, #1556 
* Remove `DIST_DIR` constant introduced in #1366 / #1352. You can choose to implement this on your own moving forward as it's not something we recommend changing.
* Move Soil theme support into setup function — dependent on https://github.com/roots/soil/pull/120 (will tag a new Soil version)
* Move CSS/JS enqueues to setup.php

Setup organization

---

assets/manifest.json
assets/styles/layouts/_tinymce.scss
assets/styles/main.scss
lib/setup.php

This is in response to https://github.com/roots/sage/issues/1552.
After playing around, I think the best solution is just to add a `_tinymce.scss` file in `/assets/layouts/` where we target the tinymce editor and can put conditional styles in there, and then just reference the main.css file in the wp editor.
This cuts styles compiling time of the default repo in half (roughly) because we're no longer creating 2 files, and no longer referencing a large scss file and injecting it into another one.

Simplify/speed up editor style process.

---

assets/styles/components/_wp-classes.scss

I came across an issue with images being stretched in posts when using the class `.alignnone`. If the image's width is greater than that of the container's, the image will shrink to fit the container but the original height is still being declared in the img tag with `height=""`. As a result, the image is being stretched vertically. Adding `height: auto;` to `.alignnone` will resize the image vertically to maintain it's original aspect ratio.

add auto height to .alignnone to prevent vertical stretch of image

---

assets/styles/components/_wp-classes.scss

Extending on https://github.com/roots/sage/pull/1565, `.alignleft`, `.alignright` and `.aligncenter` also skew vertically when the image width is wider than the container. Adding `height: auto` to these classes will override the `img` tag's height property and properly scale the image across different breakpoints.

wp-classes alignment (right, left, center) height set to auto for proper scaling

---

CHANGELOG.md
base.php
gulpfile.js

Dropped support for IE 8, IE 9, and Android 2.3.
Outdated browser warning is displayed for IE 8 and IE 9 users.

Drop support for older browsers

---

CHANGELOG.md
assets/manifest.json
assets/scripts/customizer.js
functions.php
lib/customizer.php

two new files:
* `lib/customizer.php` — add postmessage support and enqueue customizer js
* `assets/scripts/customizer.js` — js for the theme customizer. currently changes the site name in the header when it's updated from the customizer

Add support for theme customizer

---

CHANGELOG.md
assets/styles/main.scss

Sass doesn't need the underscore that's present in the filename when doing an import

Remove unnecessary underscore

---

.gitignore

`composer create-project` (see 6a6ff885360a96b70d9e883f24ab73435762dbc4) adds vendor directory which we do not want to have in version control.
composer.json and composer.lock should probably also be ignored – at the moment they are only covered by Bedrock's gitignore file.

gitignore composer vendor directory

---

config.json
dev.js
package.json
src/admin.php
src/setup.php
watch.js
webpack.config.js

- not using any environment variables in the npm scripts for better windows compatibility (removed SAGE_ENV)
- extracted options to a config file
- dist/ keep the same assets folder structure (images/, fonts/, styles/, scripts/) - this work better with the assets loaded via php as it expect subfolders to the dist folder
- webpack.config has settings specific to the "watch" script
- renamed the watch script to watch.js
- add image-webpack-loader for optimization

webpack implementation improvements

---

composer.json
composer.lock
functions.php

The Composer Autoloader has issues with the "files" directive in composer.json when Sage 9 is included as a package in a Bedrock project via the root composer.json.
After diagnosing, I don't see a way the "files" directive can be used in the Sage composer.json and not cause issues with load order.  The root composer package (in Bedrock) will see the files directive in the package and automatically attempt to load prior to WordPress. 
psr-4 autoloading for Roots\Sage should still work fine in this scenario since these are lazy-loaded.
I've moved the offending 4 files from autoloader back into functions.php the way they were in Sage 8.  I'm not sure if there is a more clever way to do this, but it fixes the issue.

Fix autoloader load order issue when including Sage 9 via composer.json in Bedrock

---

.github/ISSUE_TEMPLATE.md

Just trying to get the ball rolling on https://github.com/roots/sage/issues/1619
Inspired by several other GitHub Issue Templates, including [Yoast SEO](https://github.com/Yoast/wordpress-seo/blob/master/ISSUE_TEMPLATE.md).
Open to suggestions on this one. We probably wouldn't want to ask too much up front (such as making them list their WordPress plugins), but asking for OS and NPM/Node versions can be quite handy when troubleshooting.
Also looking for some good examples of Pull Request Templates, but I think the Roots team is going to be more qualified to set those up :smile:

Create prototype of GitHub Issue Template

---

.travis.yml

> Via https://docs.npmjs.com/cli/prune
> > This command removes "extraneous" packages. If a package name is provided, then only packages matching one of the supplied names are removed.
> >
> > Extraneous packages are packages that are not listed on the parent package's dependencies list.
The reason for adding this is to go hand in hand with the Travis CI caching implemented a while ago, if you don't run `npm prune` periodically then older packages will not be removed from the cache and the cache will continue to grow in size.
I suspect if you compare the Travis CI cache size between master and this PR, this PR will be significantly smaller. (You could also inspect the cache with Travis CI CLI I think)
https://travis-ci.org/roots/sage/caches

Add `npm prune` to Travis CI

---

templates/partials/head.php

Fixes a [viewport bug](https://developer.apple.com/library/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html#//apple_ref/doc/uid/TP40014305-CH9-SW36) in Safari 9.0

Updated to align with the Bootstrap 4 docs

---

webpack.config.js

Remove path.extname() check to fix build:production task.
Currently path.extname() is being supplied an object when it expects a string, resulting in a fatal error during production builds.
Removal is the cleanest solution as it's an unnecessary check, assets[name] will always be an object.

Remove path.extname() check

---

src/setup.php

String passed to asset_path needs to contain the directory name, otherwise it 404s on the post/page admin screen.

Fix path to stylesheet in add_editor_style

---

assets/config.json
webpack.config.js

This PR addresses the issues here : https://github.com/roots/sage/issues/1694
- Added a new file-loader for assets in node_modules. The loaders moves fonts and images to dist/vendor/... and not _/node_modules/.../...
- Put back [path] in other loaders to respect the subfolder tree in assets/images and assets/fonts
- Removed hash on images file name to be able to load them with App\asset_path
- Removed config vars that should not be changed (assets path, dist path)

move assets found in node_modules/ to dist/vendor; simpler assets/config.json

---

README.md

Readme now has instructions on how to run `npm watch` without bedrock

README updated for running browsersync without bedrock

---

assets/styles/components/_grid.scss

Rather @include make-col-ready() as opposed to using @extend %grid-column for classes main and sidebar.
http://v4-alpha.getbootstrap.com/layout/grid/

Update _grid.scss to use @include make-col-ready() mixin

---

src/admin.php
src/filters.php
src/helpers.php
src/lib/Sage/Asset.php
src/lib/Sage/Assets/JsonManifest.php
src/lib/Sage/Assets/ManifestInterface.php
src/lib/Sage/Template.php
src/lib/Sage/Template/Partial.php
src/lib/Sage/Template/Wrapper.php
src/lib/Sage/Template/WrapperInterface.php
src/setup.php

namespace declaration on the same line as <?php isn't being used much anymore. Both PHP FIG and Laravel show the namespace on it's own line.
Reference:
http://www.php-fig.org/psr/psr-2/
https://github.com/laravel/laravel/blob/master/app/User.php#L1-L3

Namespaces on own line

---

package.json

Webpack `2.1.0-beta.23` has breaking changes related to the configuration structure, so forcing `2.1.0-beta.22` as a temporary fix by removing the `^`.

Fix #1720: Specify absolute version of Webpack

---

assets/build/config.js

The two same values get concatenated. A console.log output of `watcherConfig` in `webpack.plugin.browsersync.js` : 
```
{ 
host: 'localhost',
port: '3000',
proxy: 
{ target: 'https://example.dev',
middleware: [ [Object], [Object] ] },
files: 
[ 'templates/**/*.php',
'src/**/*.php',
'templates/**/*.php',
'src/**/*.php' ]
}
```

Fix duplicate value in Browsersync files Array

---

assets/build/webpack.config.watch.js

The options added in "browserSyncOptions" in config.js were not being merged to the watch config.
This fix the issue https://discourse.roots.io/t/sage-9-configure-browsersync/7808

Fix browserSyncOptions in config.js not being passed to BrowserSync

---

assets/build/webpack.config.js

Fixes the build error
`ERROR in ./assets/images/favicon.ico
Module parse failed: ...sage/assets/images/favicon.ico Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
@ multi files`

Add support for .ico files

---

composer.json

The version constraint for `illuminate/view` should probably be tighter, as Laravel follows their own flavor of Semver in which breaking changes are allowed between minor releases.
This could potentially create a situation where simply running `composer update` could break the site (eg. after 5.4 is released).

Tighten version constraint for illuminate/view

---

functions.php

Checks for all requirements and throws an error if one isn't met.
* Minimum PHP version (`>= 5.6.4`)
* Autoloader (from Sage directory, Bedrock, or whatever; just has to be able to access Container class)
* Required files
* helpers.php
* setup.php
* filters.php
* admin.php

Throw errors if minimum requirements aren't met

---

composer.json
composer.lock
functions.php
src/filters.php
src/helpers.php
src/lib/Sage/Config.php
src/setup.php

Because we run `bindIf` on the container, this won't interfere if someone else is already using their own config binding, assuming they're implementing array and repository interfaces.
Binding is run immediately instead of in an action hook so that we can use it in functions.php.

Use Config object to store config options

---

CHANGELOG.md
assets/styles/common/_variables.scss
package.json
yarn.lock

this also drops the flexbox option we previously enabled, since bs4 is now flexbox by default (and without the option to disable)
http://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

Update to Bootstrap 4 Alpha 6

---

functions.php
src/setup.php

closes #1791 
customizer still won't work prior to theme activation which might be on hold until https://core.trac.wordpress.org/ticket/13239

Only disable customizer if theme isn't activated

---

assets/build/config.js
assets/build/webpack.config.js
assets/build/webpack.config.optimize.js
assets/config.json

As sage is a starter theme it shouldn't make hardcoded assumptions about which browsers are supported. This PR allows users to override the default browser array passed to autoprefixer. It also passes this array on to cssnano to avoid stripping intentional vendor prefixes.

Allow browser versions to be configured in config.json

---

CHANGELOG.md
assets/styles/main.scss
package.json

font awesome was added in sage 9 mainly to provide a good example out of the box on how to add a 3rd party package
there's a few issues:
* not everyone wants it
* font awesome includes formats that aren't necessary right now (https://github.com/FortAwesome/Font-Awesome/issues/10470)
* produces webpack warnings about the entrypoint size limit out of the box
this will instead be moved to the docs

Remove Font Awesome

---

composer.json
composer.lock
src/lib/Sage/PostCreateProject.php

when creating a new sage project (`composer create-project roots/sage your-theme-name`) you will be prompted:
```
Remove Bootstrap? [y,N]?
```
if yes, bootstrap is removed from:
* `package.json`
* `assets/styles/main.scss`
* `assets/scripts/main.js`
* contents of these files are cleared out:
* `assets/styles/components/_comments.scss`
* `assets/styles/components/_forms.scss`
* `assets/styles/components/_wp-classes.scss`
* `assets/styles/layouts/_header.scss`

Add option to remove Bootstrap when creating project

---

CHANGELOG.md
README.md
composer.json
src/lib/Sage/PostCreateProject.php
style.css

now allow for `style.css` / theme headers to be customized upon creation of a sage project:
since we're requiring composer and it's the recommended way to create a new sage project, we've got a lot of options.
(such as allowing users to remove bootstrap on project creation (#1810))
follow up PRs will include the ability to change theme slug, add font awesome, and possibly more.

Add option to change theme file headers

---

CHANGELOG.md
README.md
composer.json
src/lib/Sage/PostCreateProject.php

Add option to select CSS framework, add Foundation as an option

---

src/lib/Sage/PostCreateProject.php

The `PostCreateProject::addFontAwesome()` method loads and updates the contents of `package.json` but does not currently write the modified file to the filesystem, which causes the issue described in #1818. This PR fixes this.

Write modified package.json with Font Awesome (fix #1818)

---

CHANGELOG.md
README.md
composer.json
src/lib/Sage/PostCreateProject.php

new addition to the post-install options — options for setting the path to the theme folder and defining your local development URL (defined in `assets/config.json`)

Add option to configure build settings

---

.travis.yml

NPM no longer supports Node 0.10.36 which is used by Travis CI by default, resulting in failed builds. This PR specifies that Travis should use Node 4.x when building, as stated in the project requirements.

Use latest Node 4.x in Travis CI builds (Sage 8)

---

assets/styles/common/_variables.scss
bower.json
gulpfile.js

This PR is basically just a rebased version of #1814 with a few whitespace and indentation fixes, sqashed down to two commits. It addresses the `gulp watch` issue mentioned on [Discourse](https://discourse.roots.io/t/jshint-crashing-gulp-when-a-javascript-error-occurs/6783).
It also updates Bootstrap to version 4.0.0-alpha.6 and removes the `$enable-flex` var.

Fix gulp error handling (Sage 8)

---

gulpfile.js

Image minification options (specifically SVG plugin options) were not
working when using the latest version of gulp-imagemin due to a new
options passing structure, see:
https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0

Fix gulp imagemin options

---

assets/build/webpack.config.watch.js

This makes it possible to watch files on a different URL than what is configured in `assets/config.json`.
I find this useful when working with a Multisite install on sub-domains and want to watch while working on a sub-site.
Or when working together with developers that have a different LAMP stack than Trellis. This doesn't require changing and commiting changes to `assets/config.json` simply start the process with:
`DEVURL=https://subsite.example.dev npm start`

Check for dynamic env DEVURL before config

---

functions.php

Sage checks if the version of PHP installed is less than 5.6. However, if the installed version of WordPress is less than 4.7, a fatal error is thrown. This check produces a more friendly "Sage Style" error instead of a boring default php fatal error. 
See: https://discourse.roots.io/t/undefined-function-app-get-theme-file-path/8455

Add version check for WordPress version less than 4.7.0

---

templates/partials/content-page.blade.php
templates/partials/content-single.blade.php

wp_link_pages is displayed twice.
Need to add 'echo'=>0 as parameter to avoid it.

wp_link_pages displayed twice

---

app/helpers.php

Since Illuminate 5.4, `$container->make` with `$parameters` is `$container->makeWith` : https://github.com/illuminate/container/blob/8fbb101a6081786e830cb89d1a1faa846c2c0442/Container.php#L547-L568
Related: 
* https://github.com/roots/sage/commit/f242cb50e9033af815ec56c7346d7f9da4b23460
* https://github.com/illuminate/container/commit/1fc0d2451e23d2ea73c10462d74add4767e2b74c

illuminate: container make with parameters

---

package.json
resources/assets/build/config.js
resources/assets/build/webpack.config.js
resources/assets/build/webpack.config.optimize.js
resources/assets/config.json
yarn.lock

An article released by the developers of Autoprefixer and Browerslist with the release of Autoprefixer 7 strongly recommends storing your list of target browsers in `package.json`, to make it accessible to other pieces of software that may want access to it. The article can be found here: [evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released](https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released)
This pull request implements that recommendation, and updates Autoprefixer to 7.1.1.

Update Autoprefixer and standardize browserlist location

---

resources/assets/build/webpack.config.optimize.js

I was running into some issues on production builds with z-indexes as well as a few more advanced background gradients, etc. [This issue](https://github.com/vuejs-templates/webpack/issues/614) linked to a solution I thought I should try which fixed it right away. By default I think this should be included in all builds.

Optimize CSS Assets safe = true

---

resources/functions.php

In the functions.php there are some left-over mentions of the theme files being found in themes/sage. With the latest release, they're now in themes/sage/resources. This PR updates the doc comment to reflect those changes.

Update inline documentation to reflect correct theme file locations

---

README.md
composer.json
composer.lock
resources/controllers/About.php
resources/controllers/App.php
resources/controllers/Home.php

adding @darrenjacoby's controller by default
https://github.com/soberwp/controller
any thoughts on simple examples to provide out of the box? similar to https://github.com/roots/sage/tree/master/resources/assets/scripts/routes

Add soberwp/controller

---

.travis.yml
CHANGELOG.md
README.md
composer.json
resources/functions.php

recent updates accidentally made php 7 the required minimum version and we're gonna roll with it.
closes #1933

PHP 7+ is now required

---

resources/assets/build/webpack.config.js

This is in reference to #1945, I figured out what was wrong. Bootstrap's [dropdown documentation](https://getbootstrap.com/docs/4.0/components/dropdowns/) indicates the "umd" version of Popper (poorly; you have to look at the actual URL they link to) which fixes the issue of dropdowns not working in Sage Beta 4.

Fix Popper for Bootstrap 4

---

.travis.yml
CHANGELOG.md
README.md
assets/styles/common/_variables.scss
assets/styles/components/_wp-classes.scss
bower.json
gulpfile.js
package.json
style.css

https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/
this bower + popper.js integration is pretty awkward. can someone please test this out and confirm it works for them?

Sage 8.5.2 / Bootstrap 4 Beta

---

app/helpers.php

This is in reference to, and closes #1857
Code credit goes entirely to @Kimers. I just made it into a PR.

Fix for plugins that don't enqueue their scripts properly

---

package.json

Fix #1950 by not relying on the user's shell but rather passing the unexpanded pattern directly to `stylelint` which in turn expands it using `node-glob`.

Issue #1950: Fix lint:styles script not matching files in deep subdirectories

---

app/helpers.php
resources/controllers/App.php
resources/views/partials/page-header.blade.php

Apart from being another controller example, I think it makes more sense the `title()` method being inside the `app.php` controller instead of the `helpers.php` (which has much more blade related code than "templating" code).

Moved title() helper to app.php controller

---

app/helpers.php

I was reading the solution (#1939) to fix #1936 and came up with an alternative fix by changing the 
```php
return collect($templates)
->map(function ($template) {
return preg_replace('#\.(blade\.)?php$#', '', ltrim($template));
})
...
```
with 
```php
return collect($templates)
->map(function ($template) {
return basename(basename(ltrim($template), '.php'), '.blade');
})
...
```

Ensure templates filenames without path and extension.

---

package.json

See https://github.com/roots/sage/pull/1951#issuecomment-323593159
Note that I haven't tested this on windows.

Followup #1950: Fix lint:styles task with cmd.exe

---

README.md

Aligns readme.md with the relocation of `controllers` in #1954 and #1959, and reflects the removal of `app/lib/Sage` in #1919.

Move /controllers to app, remove app/lib/Sage in readme

---

package-lock.json
package.json
resources/assets/build/webpack.config.js
yarn.lock

console errors were accidentally disabled, now they're back
ref https://discourse.roots.io/t/command-line-lint-errors-gone-in-beta-4/10227

Add friendly-errors-webpack-plugin

---

resources/assets/styles/autoload/_bootstrap.scss
resources/assets/styles/common/_variables.scss
resources/assets/styles/main.scss

Move variables and Bootstrap lines to autoload

---

resources/assets/config.json

ref
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
https://github.com/roots/trellis/issues/580
https://github.com/roots/trellis/pull/923

Change .dev to .test for default local dev TLD

---

package-lock.json
package.json
yarn.lock

After years of development a release version of Bootstrap 4 has landed 👍 
• Updated bootstrap to release version 4.0.0
• Updated popper.js to version 1.12.9

Updated bootstrap to release version 4.0.0

---

.travis.yml
CHANGELOG.md
README.md
composer.json
composer.lock

[something down the dependency tree is now requiring 7.1](https://travis-ci.org/roots/sage/jobs/350031800)

PHP 7.1+ is now required

---

resources/views/index.blade.php
resources/views/layouts/app.blade.php
resources/views/page.blade.php
resources/views/partials/comments.blade.php
resources/views/partials/content-page.blade.php
resources/views/partials/content-search.blade.php
resources/views/partials/content-single.blade.php
resources/views/partials/content.blade.php
resources/views/partials/footer.blade.php
resources/views/partials/head.blade.php
resources/views/search.blade.php
resources/views/single.blade.php
resources/views/template-custom.blade.php

According to https://github.com/roots/sage/issues/2012 issue, Laravel 5.5 dropped support for inline `@php` directive like `@php()`. On this PR I changed every inline to full form. I've already reproduce the issue on my sage-woo fork.

Changed inline @php directive to full form

---

resources/views/partials/comments.blade.php
resources/views/partials/sidebar.blade.php

Looks like a few leftover shorthand php directives.

Remove php blade shorthand

---

app/helpers.php

All sage/filter_templates/paths have now higher priority than stand-alone template files. Fixes #1979.

Update template hierarchy

---

CHANGELOG.md
resources/assets/build/webpack.config.watch.js

sage-installer doesn't set `proxyUrl` to `https` if you provided an `https` URL for your `proxyUrl`, resulting in issues with browsersync sessions
rather than forcing it in sage-installer, here we're detecting which scheme to use based on `devUrl` and overriding it for `proxyUrl`

Auto-detect proxyUrl scheme

---

app/helpers.php

This prevents template() from enqueuing styles and scripts intended for the front end, when used in the admin.

Make template() compatible with wp admin

---

resources/assets/build/webpack.config.optimize.js

Disable removal of the SVG viewBox by default to improve compatibility. See this Discourse thread: https://discourse.roots.io/t/svg-size-change-upon-yarn-build-production/12320

Proposal: Set removeViewBox to 'false' in webpack's optimization settings

---

resources/assets/build/postcss.config.js
resources/assets/build/webpack.config.js

I was looking into a fix for #2077 and here’s what I discovered:
- `cssnano` was not the issue with the above mentioned issue the desired functionality works perfectly when using normal CSS instead of Sass.
- Sass removes the source comments by default.
- So even disabling `cssnano` completely still resulted with the same issue.
- [Autoprefixer requires `/*! autoprefixer: off */` in Sass and Less](https://github.com/postcss/autoprefixer#control-comments).
- When processing Sass, comments are removed before the PostCSS plugins are processed.
- PostCSS plugins (i.e. Autoprefixer, Purgecss) often use comments for processing so we need them to be there when that processing takes place.
- We still want `cssnano`’s `discardComments` set to `removeAll: true` since we don’t want any comments in …

Enable Sass comments and run prefixing before minification

---

.eslintrc.js
package.json
resources/assets/build/webpack.config.optimize.js
yarn.lock

Simply use UglifyJs plugin instead of Webpack built-in version which allows us to configure it. I'm including one useful feature to drop console.log statements to avoid eslint errors on `build:production`
Related to discourse discussion: https://discourse.roots.io/t/uglifyjs-error-on-production-build/12419/4?u=jasonbaciulis

Add uglifyjs plugin

---

resources/assets/build/webpack.config.js

This checks for a `webpack.config.preset.js` file in the `build` directory. This is a useful feature for the installer, giving us the ability to add preset specific modifications to the `webpack.config.js` without needing to make a copy of it in the `sage-installer` repo.
h/t to @QWp6t and @mmirus

Add support for preset specific Webpack config

---

app/filters.php
resources/views/partials/searchform.blade.php

Inspired by this thread:
https://discourse.roots.io/t/custom-search-form/9079
The WordPress searchform, and the ability to customize it, is basic WP functionality that Sage unintentionally breaks. This PR predictably replaces the WP default template with a Blade partial, much like the the comments partials we already ship, letting users use [get_search_form()](https://developer.wordpress.org/reference/functions/get_search_form/) as normal.

Add searchform partial and function to replace default WordPress functionality

---

resources/views/layouts/app.blade.php

https://developer.wordpress.org/reference/functions/get_language_attributes/
https://developer.wordpress.org/reference/functions/language_attributes/#source
```
craig [5:23 PM]
PRs accepted
```

Change language_attributes() to get_language_attributes()

---

resources/assets/build/webpack.config.js

Using `merge.smartStrategy` with `'module.loaders' = 'replace'` to load the preset config allows presets to override the the default webpack config. This is necessary for [the coming Tailwind preset](https://github.com/roots/sage-installer/pull/22) which requires `resolve-url-loader` and source maps to be disabled.

Use better merge method for Webpack Preset config

---

composer.lock

Updates `roots/sage-installer` to 1.4.1.
Includes a new Tailwind CSS preset and fixes a bug where certain paths needed to be escaped for the `postCreateProject` scripts to run.

Bump sage-installer

---

resources/assets/build/webpack.config.optimize.js

I recently had a problem with the [ecma option of UglifyJs](https://github.com/mishoo/UglifyJS2/tree/harmony#minify-options) being set to `8`.
One of my packages was using [bn.js](https://github.com/indutny/bn.js/) as a dependency and [this block of code right here](https://github.com/indutny/bn.js/blob/e69c617b3297b99aca429f30842e27979ef9beb5/lib/bn.js#L2600-L2604) was compiled to `return{a,b:f,gcd:i.iushln(c)}}` and of course the `a`  threw an `SCRIPT1003: Expected ':'` error in Internet Explorer because it doesn't support the new [EcmaScript 6 Property Shorthand syntax](http://es6-features.org/#PropertyShorthand). I had no idea what it was and how to fix it until I found [this solution](https://stackoverflow.com/a/50876566) so that's why I am fixing it here in this repo.
To change the …

UglifyJs: Change the ecma option from 8 to 5

---

app/filters.php

---
**What is the current behaviour?**
Compiled comments template is included directly and that causes the error with missing $__env variable and that causes that e.g. @foreach cycle doesn't work.
**What is the expected or desired behavior?**
Comments template is rendered with Blade's render method.
---
**Please provide steps to reproduce, including full log output:**
1) add the following code to `partials/comments.blade.php`
```php
@foreach([1,2,3,4,5] as $i)
{{ $i }}
@endforeach
```
2) an error occures
**Please describe your local environment:**
WordPress version: 4.9
**Where did the bug happen? Development or remote servers?**
Everywhere
**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?** …

Comments template fix

---

resources/views/layouts/app.blade.php

`get_language_attributes()` shouldn't be escaped in `app.blade.php` as brought up here https://github.com/roots/sage/pull/2089#commitcomment-30412267

Unescape get_language_attributes()

---

app/filters.php
resources/views/partials/searchform.blade.php

Reverts roots/sage#2090
Closes #2105 #2109

Revert "Add searchform partial and function to replace default WordPress functionality"

---

CHANGELOG.md
composer.json
composer.lock
package.json
resources/style.css

i accidentally bumped `illuminate/support` to `5.7` with #2111 which prevented the sage-installer from working 
thanks @mmirus for pointing this out!

9.0.4: Force `illuminate/support` to `5.6.*`

---

app/filters.php
app/helpers.php

This brings hook run sequence in line with expected WordPress theme behavior, and solves compatibility issues with plugins that relies on this expected behavior. It also moves the initial execution of get_header, wp_head and their child hooks to before the data filters. The logic in controllers will happen closer to where that logic it is expected to happen in relation to the hook system.
This solves the issue described in #2116.

Hook run sequence fix

---

resources/assets/scripts/util/Router.js

It is especially neat when importing the scripts from the parent theme in a child theme. In one of my themes I do it like this:
```js
// routes.js
export default {
home: {
init() {
console.log('Home route fired.')
}
}
}
```
```js
// main.js
/**
* Parent Themes Script
*/
import '../../../../core-theme/resources/assets/scripts/main';
/**
* Internal modules
*/
import routes from './routes'
/**
* Hook in to the parent themes router
*/
document.addEventListener('routed', e => {
let route = e.detail.route,
fn = e.detail.fn;
if (routes[route] && typeof routes[route][fn] === 'function') {
routes[route][fn]();
}
});
```

Dispatch event when firing routes

---

.gitignore

Hi, team. Thanks for great project! I appreciate it very much!
Here is my tiny suggestion, I am very happy if you can consider it.
If there is a plugin containing a vendor directory([like this](https://wordpress.org/plugins/wp-nested-pages/)), it will be ignored, so why not just ignore the vendor directory in the root?

Do not ignore vendors for plugins

---

resources/views/partials/content-search.blade.php
resources/views/partials/content-single.blade.php
resources/views/partials/content.blade.php

Don't escape post titles. Fixes problems with special characters like quotes.
Consistent with: https://github.com/roots/sage/blob/master/resources/views/partials/page-header.blade.php

Unescape post titles

---

resources/assets/build/webpack.config.optimize.js

After seeing the following graph [here](http://sweetme.at/2013/09/11/how-to-maximize-png-image-compression-with-optipng/) we decided to test optimsation level 2 for OptiPNG instead of 7. This is because, acording to the graph we would notice no real difference in avarage file size but would notice a speed increase with our builds.
After testing , we noticed our theme build go from a build time of over 10 mins (just on the 94% asset optimisation step) to an avarage of `150.75s`. All the while, we only gained 10-15kb per png file which we believe more than reasonable for a build speed increase of this magnatude.

Decrease optipng level

---

app/filters.php

Add `embed` to the template hierarchy filters in Sage, so that the embed template can be overridden from the `views` folder.
Closes #2142 
Once this is merged, you can copy `wp-includes/theme-compat/embed.php` to `views` and adapt it however you want, just like any template file in Sage. Better yet, create `views/embed.blade.php` , with something like:
```blade
@include('partials.header-embed')
@if (have_posts())
@while (have_posts()) @php the_post() @endphp
@include('partials.embed-content')
@endwhile
@else
@include('partials.embed-404')
@endif
@include('partials.footer-embed')
```
The above assumes that you've also added `embed-content`, `embed-404`, and `footer-embed` templates to the `partials` folder, but you don't have to if you don't need to customize them.

Filter template hierarchy for embed templates

---

CHANGELOG.md
composer.json
composer.lock
package-lock.json
package.json
resources/style.css
yarn.lock

https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/

Update to Bootstrap 4.3.0 (9.0.8)

---

package.json
yarn.lock

This lets us run related scripts together pretty easily since we can use glob patterns (e.g. `lint:*` — `**` is supported too). You can either run scripts sequentially with `run-s` or in parallel with `run-p`.
See: https://github.com/mysticatea/npm-run-all

Add npm-run-all

---

.gitignore
README.md
app/Providers/ThemeServiceProvider.php
app/setup.php
config/app.php
config/view.php
resources/assets/scripts/app.js
resources/assets/scripts/customizer.js
resources/assets/scripts/routes/about.js
resources/assets/scripts/routes/common.js
resources/assets/scripts/routes/home.js
resources/assets/scripts/util/Router.js
resources/assets/scripts/util/camelCase.js
resources/functions.php
storage/framework/cache/.gitignore
storage/framework/cache/data/.gitignore
storage/framework/views/.gitignore
webpack.mix.js

- Add `name` configuration to `config/app.php` (defaults to theme name).
- Move default cache location to `storage/`.
- Add a ServiceProvider stub.
- Add missing trailing commas to configs.
- Remove/revert automatic Blade cache removal action as it is no longer necessary.
- Clean up `.gitignore`.
- Clean up JavaScript docblocks.
- Remove `home.js` example leaving `about.js` to give an example of camelCase.
- Remove leftover Sage 9 information from the readme.
- Move the DOM-based router to it's own package.
- Change Acorn's manifest/asset class to handle leading slashes.
- Figure out a solution to handle `images` and `fonts` versioning (attempt a PR into Laravel Mix?)
- Decide on a solution for changing cache busting from args to filenames …

Continued Sage 10 cleanup

---

package.json

Since views are in a predictable location within the theme, this might be handy. A side effect of adding this is that generated views are now cleared on every production build, which might be a good thing. If not, it’s not hard to change.

[Sage 10] Add clean:views npm script

---

webpack.mix.js

Since Mix uses the `webpack.mix.js` path as the webpack context and doesn’t let us change the context, having a helper can make it easier to add new assets. It also provides a single source of truth for the assets source directory (one less thing to _mix_ up — pun intended).
Also, this adds a `public` function which just makes it easy for setting the `from` path in the `copyDirectory` task.
I figure by including the definitions of these functions within the `webpack.mix.js` file itself it makes it clear to Sage users that they are not a part of Mix.

[Sage 10] Add src and public mix path helpers

---

webpack.mix.js

* Combine watch rules using extended glob patterns (tested + works).
* Use template literals for the mix helpers. Makes it seem less cluttered since we lose a bunch of parentheses.
* `public` is a future reserved word in JS so I switched it to `out` (other suggestions welcome).

[Sage 10] Minor syntax changes + publicPath helper name change

---

resources/assets/scripts/app.js
resources/assets/scripts/utils.js

Replacements of jQuery’s `$(document).ready()` function usually look something like this:
```js
function ready(callback) {
if (document.readyState === 'complete' || document.readyState === 'interactive') {
return callback();
}
document.addEventListener('DOMContentLoaded', callback);
}
```
`document.readyState === 'complete'` is [just for IE 8](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#Browser_compatibility) — which we don’t support. `document.readyState === 'interactive'` is for everything IE9+, but it also [happens in the same sequence as `DOMContentLoaded`](https://html.spec.whatwg.org/multipage/parsing.html#the-end) which is [supported by everything that is relevant](https://caniuse.com/#search=DOMContentLoaded).
I think …

[Sage 10] Replace jQuery’s .ready()

---

functions.php

I just noticed this, but even on Sage 9, our current use of `>=` on our conditionals would effectively make (in Sage 9's case) `7.1` and `4.7.0` return an error (as they would evaluate the conditional to `true`) even though they are supposed to be considered the supported minimums.
Using `>` instead fixes this issue, but as-is our use of `version_compare()` and it's operator are a little confusing at a glance. We should perhaps swap our required version and their current version in the function as seen [here](https://www.php.net/manual/en/function.version-compare.php) so we can use the `less than` sign instead.
Right now it kind of reads as "if `7.1.3` is greater than `phpversion()`" when instead it should read as "if `phpversion()` is less than `7.1.3`"

Fix version_compare() operators

---

package.json
webpack.mix.js
yarn.lock

Since upstream changes were merged which make the default files to watch use the publicPath (JeffreyWay/laravel-mix#2091). One caveat is that those the default files to watch don’t include `config/*.php`, but the impact for us would be low since those files probably won’t be changing a ton. It could be something we make another upstream PR for since it could be beneficial to the Laravel community as well.
~~Leaving this as a draft for now since we’ll need to update the Laravel Mix dev-dependency once it gets tagged.~~

[Sage 10] Simplify Mix Browsersync API

---

package.json

Previously mentioned here https://github.com/roots/sage/commit/f5c5d2844c438ba53e9571c67e96871a3b92b1e8#r33668278
This is a known difference between yarn and npm and will eventually break with yarn once backwards compatibility is removed.
Currently it will cause this warning with Yarn:
> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
Once Yarn removes the backwards compatibility this script will cause the following broken command to run:
```sh
webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js -- --watch
```
As this will eventually break I'm not sure if this the way to go but sending a PR so the issue is documented.
This behavior …

Fix npm run start script options not forwarded with npm

---

package.json
yarn.lock

A few tools we’re already using (Babel, Autoprefixer, Stylelint, ESlint) use Browserslist under the hood for their target browsers. I think explicitly setting it would be helpful for developers using Sage since it will encourage them to configure it themselves instead of relying on the invisible default setting ("defaults").
I’m using the `browserslist` key in `package.json` as the method since [it’s recommended](https://github.com/browserslist/browserslist#queries), however, we can always split this out to its own config file (`.browserslistrc`). I think the former is better since `package.json` is a heavily used file and it will make it very clear to the developer which browsers they are supporting. A file that lists dependencies also makes sense to provide a list of compile targets. …

Use WordPress’ Browserslist config

---

config/assets.php

Acorn now uses an Asset Manager to make it easier for themes and plugins to include multiple manifests. This is helpful for plugins to use their own manifests, and it's also helpful for child themes to add their own manifests while also loading the manifests of the parent theme.
Simple example usage can be found in this PR:
https://github.com/roots/acorn/pull/23
Upon merging this PR, we will need to update Sage 10 to use the latest version of Acorn as well, perhaps Acorn alpha release should be tagged before this is merged?

Acorn asset manager config

---

webpack.mix.js

Resolves #2266
Laravel Mix has a bug where source maps are not generated if you do not specify the source map type (the second argument). This corrects that.

Fix broken source maps and remove unnecessary conditionals

---

app/filters.php
composer.lock
config/view.php
resources/views/partials/content-single.blade.php

This is to be merged after https://github.com/roots/acorn/pull/32 is merged.
- Move `get_search_form` and `body_class` filters to Acorn.
- `comments_template()` now defaults to `partials/comments.blade.php`.
- Composers are now autoloaded.

Updates to reflect Acorn

---

app/Composers/Title.php
composer.lock
package.json

Adds translation commands to `package.json`. Includes support for Javascript (`wp i18n make-json`).
Adds translator comment to placeholder string in `app/Composers/Title.php`.
Does not implement the loading of translated strings as this is a costly operation as implemented in core and I don't want to sully the pristine `setup.php` with a caching utility that would probably be better housed in `app/plugins`.

Adds i18n support

---

app/setup.php

required by webpack if using `.extract()`

Inline manifest.js when enqueueing editor.js

---

app/setup.php

Just adds a single theme color. 
Alternatively, we could disable theme color support.
If desired I can open a separate PR to handle disabling custom font-sizes. I think it's a good idea for them to ship disabled, personally.

Add theme color palette support

---

webpack.mix.js

When organizing image and font assets in subdirectories their paths are flattened eg. `resources/assets/images/foo/bar.png` -> `dist/assets/images/bar.png`
With this PR it becomes `dist/assets/images/foo/bar.png`
At first I thought this was a bug in the `laravel-mix-copy-watched` package ([invalid bug report](https://github.com/dsktschy/laravel-mix-copy-watched/issues/10)) but turns out it works as intended and keeping the hierarchy is actually an additional option.
I thought I'd open up a PR as others might encounter this as well. This is how it worked in sage 9, no?
Feel free to close this if you don't agree that this is a better default.

Keep hierarchical assets directory structure

---

.stylelintrc
resources/assets/styles/common/global.scss
resources/assets/styles/components/button.scss
resources/assets/styles/components/index.scss

- fix(stylelint): Fix broken tests 
- feat(stylelint): Set `at-rule-empty-line-before` to `null` to allow sane seperation of imports

Fix tests / stylelint rules

---

.babelrc
.editorconfig
app/admin.php
app/filters.php
app/helpers.php
app/setup.php
composer.json
composer.lock
index.php
package.json
resources/assets/scripts/customizer.js
resources/views/components/alert.blade.php
resources/views/layouts/app.blade.php
resources/views/partials/head.blade.php
resources/views/partials/page-header.blade.php
webpack.mix.js
yarn.lock

- fix(templates): Move the document wrapper from `app.blade.php` to `index.php` to fix hook run sequence. 
- This is the same issue seen in Sage 9 (#2123) and is due to Blade firing the hook sequence out of order when compiling. It is situationally problematic with certain plugins (e.g. Gravity Forms) and is best left to a simple fix to avoid further complications.
- **Note:** I moved `do_action('get_footer')` below the footer partial and outside of the `#app` div. Is this ok? (CC: @retlehs)
- fix(setup): Enqueue `vendor.js` with editor scripts. (Fixes #2370, #2371)
- chore(docblocks): Remove copyright/license from PHP docblocks
- chore(linting): Run linting
- chore(babel): Remove unused dynamic import plugin until Webpack 5 (#2204)
- chore(babel): Remove unused `.babelrc`
- chore(deps): …

Sage 10 fixes/cleanup

---

README.md
functions.php
style.css

See: https://make.wordpress.org/core/2020/02/26/miscellaneous-developer-focused-changes-in-wordpress-5-4/

Add `Requires PHP` and `Requires at least`; Bump WordPress requirement to v5.4

---

.circleci/config.yml

- use offical CircleCI [PHP orb](https://circleci.com/orbs/registry/orb/circleci/php)
- use offical CircleCI [Node orb](https://circleci.com/orbs/registry/orb/circleci/node)
- use offical CircleCI [next-gen docker images](https://circleci.com/docs/2.0/circleci-images/#next-generation-convenience-images)
- use [`matrix`](https://circleci.com/docs/2.0/configuration-reference/#matrix-requires-version-21)
- add PHP 7.4
- add node 12 and node 14
---
Not sure why GitHub is not reporting the build status.
See: https://circleci.com/gh/TangRufus/workflows/sage/tree/circleci

CircleCI: Use offical CircleCI PHP and Node orb, and next-gen docker images

---

app/setup.php

[soil 4 has been released](https://roots.io/plugins/soil/) which uses a different syntax for activating modules

Soil: Activation updates for latest version

---

.prettierrc

For "trailingComma" in `.prettierrc`, the value "true" is not accepted. Valid values are: "es5", "none", "all" https://prettier.io/docs/en/options.html#trailing-commas

Correct "trailingComma" value for prettier

---

package.json
yarn.lock

Since Sage is relying on WordPress’ jQuery, we can save the user from needing to download it.

Make jQuery 3.5.1 a peer dependency

---

index.php

Remove redundant x-ua-compatible meta tag

---

README.md

This updates the README to reflect changes made for Sage 10.
- Switches references to Laravel Mix to Bud.
- I am using the Netlify URL for the docs. Not sure if we want to change this.
- While jQuery still works in Sage since it works in WordPress, I removed the mention of it as a feature.

README updates for Sage 10

---

.stylelintrc

Fixes linting errors when using  `@use`, `@forward` or `@layer` in a `.scss` file.

fix(lint): Add additional known at-rules

---

CHANGELOG.md
composer.json

https://github.com/roots/acorn/releases/tag/v2.0.0-beta.5

Bump roots/acorn to v2.0.0-beta.5

---

index.php

Sounds like this was only needed from about iOS 9.0-9.3.2 (see articles for a more accurate range).
See:
- https://www.matuzo.at/blog/html-boilerplate/
- https://www.scottohara.me/blog/2018/12/11/shrink-to-fit.html
- HTML 5 Boilerplate

feat(theme-wrapper): remove `shrink-to-fit=no`

---

composer.json

closes #2852
ref https://github.com/roots/acorn/releases/tag/v2.0.0-beta.6

chore(deps): Bump roots/acorn to v2.0.0-beta.6

---

README.md
app/helpers.php
functions.php

I've removed this on every project I've made with Sage 10 up to this point as I can't really find a reason I'd use a messy global function over using a method inside of a Composer, a trait, or my own class.
Thoughts?

chore: remove helpers.php

---

index.php
resources/scripts/app.js

This PR took a bit of a turn. Originally, it moved existing JavaScript detection from the `body` to the `html` element as well as the code to do that to the `index.php` file. After some feedback and further research, I began to question the necessity of the JavaScript detection in the first place. I struggled to find websites that actually used JavaScript detection with a class name on `html` or `body` and when they did there was no code on the site that actually used the class name for any non-JS or enhanced effect.
I’m convinced that this method has lost favour to progressive enhancement methods which emphasize writing styles that work for HTML out of the box. In these methods, increased specificity (e.g. the targeting the presence of attributes) is used to style components when they …

Remove JavaScript detection using class names

---

resources/views/sections/header.blade.php

Hello,
Just a quick fix but I often come across it
When the title of our site contains the character &.
On the site side, it displays `&amp;`.

chore(header): allow unescaped siteName data

---

composer.json

https://github.com/roots/acorn/releases/tag/v2.0.0-beta.9
closes #2946

⬆️ bump roots/acorn to v2.0.0-beta.9

---

theme.json

Assuming most people using Sage will be defining their own palette, might be worth removing the defaults WP throws in there?
<table>
<tr>
<th>before</th>
<th>after</th>
<tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

🔥 remove default palette + gradients from theme.json

---

tailwind.config.js

Since `index.php` is a part of the views and can have `tailwindcss` classes, it makes sense to have it included into the purge content list to not miss any css classes there.

🔧 Add index.php to tailwindcss purge list

---

package.json

This PR adds more and improves existing translation related `npm` scripts:
- `translate`: Run `translate:pot` and `translate:update`.
This is used to update the `PO` files to the latest translatable strings in the theme.
- `translate:pot`: Update the Poedit Template (`POT`) file from the theme files.
- `translate:update`: Update `PO` translation files (for a specific locale, e.g. `de_DE`) from the Poedit Template (`POT`) file.
- `translate:compile`: Run `translate:js` and `translate:mo`.
This is used to compile all the `PO` files to `JSON` and `MO` for usage in PHP/JavaScript/WordPress.
- `translate:js`: Generate the JavaScript `JSON` translation files from `PO` files, used by JavaScript related WordPress components like Gutenberg Blocks in the Gutenberg Editor.
- `translate:mo`: Compile …

🔧 Improve translation scripts

---

resources/views/partials/comments.blade.php

This PR fixes the i18n warnings by adding a missing translators comment and uses a singular placeholder.
For single comments, `One` is used instead of a number (in a `comments title` context), which fixes the 2nd i18n warning.
Edit: Fixed something and merged commits into one, hence the force-pushes...

🐛 Fix i18n warnings

---

bud.config.js

users will be less likely to run into issues when adding dynamic imports by configuring the public path when setting up the theme
[this was required for sage 9](https://github.com/roots/sage/blob/7e6d0671d3421acadb6e9b3d0bad2a9f54d62c67/resources/assets/config.json#L11)

🔧 bud config: set the public path by default

---

bud.config.mjs
tailwind.config.cjs
theme.json

This PR
- generates `theme.json` from `bud.config.js`
- sets `theme.json` palette from `tailwind.config.js`
See: updated [@roots/sage documentation on theme.json support](https://bud.js.org/extensions/sage#generate-themejson)
TODOs

feat: generate `theme.json` from `bud.config.js`

---

bud.config.mjs

~~Default gradient swatches reappeared in the palette as of WordPress 6.1. The empty `gradients` array removes them.~~
This also removes duotone filters as while we're at it.

🔥 Remove default duotone filters from theme.json

---

app/setup.php

Noticed some `after_setup_theme` links were outdated.

💡 Update WordPress documentation links

---

.github/workflows/main.yml
README.md
app/Providers/ThemeServiceProvider.php
composer.json
functions.php

These changes are required to upgrade to Acorn v3
TODOs
Ref https://github.com/roots/acorn/releases

🔧 Acorn v3 (Laravel 9.x), drop PHP 7.4 support

---

functions.php

This PR along with https://github.com/roots/acorn/pull/266 helps better understand when a service provider is causing something to break

🧑‍💻 Check that the Acorn bootloader exists before booting

---

README.md

The README still referenced / linked Acon v2.

📝 Update README, update requirement for Acorn v3

---

package.json

This PR replaces the existing shell script with a `wp i18n` invocation for the newly added `update-po` subcommand that updates the PO files with the POT file.
This eliminates the need for external tooling (except for the `wp` CLI of course) and shell scripts. 
The latest `wp i18n` version (>=[`2.4.0`](https://github.com/wp-cli/i18n-command/releases/tag/v2.4.0#:~:text=Add%20update%2Dpo%20command)) is needed for the newly added `update-po` subcommand.
Until `wp` CLI is also newly released with the new `wp i18n` version bundled, 
the latest `wp i18n` version can be installed independently from the `wp` CLI version by using 
`wp package install wp-cli/i18n-command:dev-main` 
and then just using it as usual (`wp i18n`).

🔧 Use `wp i18n update-po` for updating PO files

---

resources/styles/app.css

Minor change to switch from older `@import 'tailwindcss/...` syntax to `@tailwind` as recommended in Tailwind docs.
This encourages users to avoid a possible cache invalidation issue.
See: https://tailwindcss.com/docs/installation#:~:text=Add%20the%20Tailwind,main%20CSS%20file.
See: https://github.com/roots/bud/issues/2455
The cache invalidation logic for `@tailwind` was introduced in Tailwind 3.0.24. [Sage's app.css was written originally for Tailwind 2.0.2 on Sage 10.0.0-beta.1](https://github.com/roots/sage/commit/5518ea165abadebff284c8cdfa32d6bab86f913a)

fix: update default app.css tailwind syntax to use @tailwind (#3149)

---

bud.config.js
theme.json

Enable background images for group blocks
Ref https://make.wordpress.org/core/2023/10/17/miscellaneous-editor-changes-in-wordpress-6-4/#how-to-add-backgroundimage-support-to-a-theme
h/t @hofmannsven via https://github.com/roots/radicle/issues/98

✨ Editor: Add background image support

---

package.json

Using `npm` for executing the translation-specific scripts (in `package.json`) makes the translation-scripts compatible with projects that are using `npm` instead of `yarn` (and where no `yarn` is installed/available for that `node` environment/version).

Use `npm` for translate scripts execution

---

app/View/Composers/Comments.php

Follow-up to #3162 that fixes this warning:
```
Warning: The string "%1$s response to &ldquo;%2$s&rdquo;" contains placeholders but has no "translators:" comment to clarify their meaning. (app/View/Composers/Comments.php:44)
```

🩹 Comments title: Fix make-pot warning

---

resources/views/partials/comments.blade.php
resources/views/partials/content-page.blade.php
resources/views/partials/content-single.blade.php

♿️ Add accessible names to nav elements

---

style.css

In #3176 the minimum PHP version is bumped to 8.1 - updated this also in `style.css`

Bump minimum PHP version to 8.1

---

.github/workflows/main.yml

* We can now simply cache yarn by just specifying a `cache` key to actions/setup-node@v4
* Replace: deprecated `COMPOSER_TOKEN` variable in favor of `GITHUB_TOKEN`.
* fix: The set-output command is deprecated and will be disabled soon.

fix: Deprecation errors in CI Action

---

app/View/Composers/Comments.php
resources/views/partials/comments.blade.php

This was annoying. 
Apparently `$comments` gets forcefully overridden when inside of the WordPress comments template. Not something I had thought about in a long time and it left me insanely confused on why I kept getting an array of comments instead of the HTML markup when setting `'echo' => false`.

🩹 Fix the comment list output

---

resources/js/build/wordpress.js
vite.config.js

Simplified implementation of WP dependency handling
Follow-up to #3199

🎨 Simplify WordPress dependency handling

---

resources/js/build/wordpress.js

Previously, `wordpressThemeJson` checked that `themeContent` starts with  `:root{`, but  Tailwind wraps theme layer  in  `:root, :host`, causing an early return.  Remove '{'  to support `:host` selector and add `trim()` for non-minified app.css.

Fix theme.json generation to handle :host selector in app.css theme layer

---

vite.config.js

Adds the same default aliases as the @roots/sage bud extension. Allows hashed asset paths to be referenced in css & js.
For example: ` background-color:url('@images/example.jpg');`

add default aliases for assets

---

vite.config.js

Setting absolute paths in aliases to prevent warnings in Vite.js and fix the background-image reference to an image using eg. @images/bg.svg

Fix default aliases paths for assets

---

resources/js/build/wordpress.js

While testing I found that the `themeContent` CSS sometimes does not contain a closing curly bracket, meaning the index of the last bracket was -1. This cut off the final `--color-example: #abcdef` definition by one character, leading to the generated theme.json color for that one to be:
````
{
"name": "example",
"slug": "example",
"color": "#abcde"
}
````
By checking for the presence of the final bracket, we can either slice to there, or to the end of the content if it is not present.
````
const endIndex = themeContent.lastIndexOf('}');
const rootContent = themeContent.slice(themeContent.indexOf('{') + 1, endIndex === -1 ? undefined : endIndex);
````

Compact fix for color generation in theme.json

---

resources/js/build/wordpress.js

Hey,
first of all, great job implementing Vite to the Sage, I love it!
Dependency extraction regex is working fine when imports are defined in single line, but not working when imports are defined using new lines, e.g.
```
import {
InnerBlocks,
InspectorControls,
RichText,
useBlockProps,
useInnerBlocksProps,
} from '@wordpress/block-editor';
```
This PR should fix regex and add check if extracted import is not empty (last comma in import block was causing trouble).
Also I've added small fix for Typescript compatibility.

Fix Vite dependency extract

---

resources/js/build/wordpress.js

Added a simple function that matches corresponding curly braces so the `@layer theme` content is correctly matched.
fixes #3220

fix tailwind css regex mismatch

---

.gitignore

When pulling down a fresh copy of Sage and running `yarn && yarn dev`, the following error occurs due to a missing `public` directory:
```
$ vite
node:fs:2426
return binding.writeFileUtf8(
^
Error: ENOENT: no such file or directory, open 'public/hot'
at Object.writeFileSync (node:fs:2426:20)
at Server.<anonymous> (file:///***/sage/wp-content/themes/sage/node_modules/laravel-vite-plugin/dist/index.js:110:14)
at Object.onceWrapper (node:events:638:28)
at Server.emit (node:events:536:35)
at emitListeningNT (node:net:1980:10)
at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: 'public/hot'
}
```
This error doesn't occur if you happen to run `yarn build` before `yarn dev`. Adding an empty `public` directory to the …

Avoid missing directory error when running `dev`

---

app/setup.php

This PR removes an unused import statement (`use Illuminate\Support\Facades\File`) from `app/setup.php`.

Remove unused `use` statement in `setup.php`

---

app/setup.php

Always import the `editor.css` instead of inlining it when Vite is not running hot.
For example `@font-face` calls require an absolute URL to the font when inlined, due to being called from within an iFrame.
I guess the same issue appears for images referenced within the CSS file.
Instead of putting absolute URL's into the CSS file we can just import the CSS file, that way it uses the hostname of the CSS file.

Always import the editor.css

---

.github/renovate.json
package.json

* Bumped npm dependencies to latest versions
* Relaxed version constraints in `package.json`
* Changed Renovate config from "bump" to "replace" strategy to reduce unnecessary PRs when latest versions are already installable within current ranges

⬆️ Bump dependencies
